jobs:
  - job: 'deploy_java'
    displayName: 'Deploy artifacts'
    # Strategy for the job => we deploy the artifacts only from Java 11
    strategy:
      matrix:
        'java-11':
          image: 'Ubuntu-22.04'
          jdk_version: '11'
          main_build: 'true'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-22.04'
    # Pipeline steps
    steps:
      # Get cached Maven repository
      - template: "../steps/maven_cache.yaml"
      - template: '../steps/prerequisites/install_java.yaml'
        parameters:
          JDK_VERSION: $(jdk_version)
      - task: DownloadPipelineArtifact@2
        inputs:
          source: '${{ parameters.artifactSource }}'
          artifact: Binary
          path: $(System.DefaultWorkingDirectory)/
          project: '${{ parameters.artifactProject }}'
          pipeline: '${{ parameters.artifactPipeline }}'
          runVersion: '${{ parameters.artifactRunVersion }}'
          runId: '${{ parameters.artifactRunId }}'
      - bash: tar -xvf target.tar
        displayName: "Untar the target directory"
      - bash: "./.azure/scripts/push-to-nexus.sh"
        env:
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          GPG_PASSPHRASE: $(GPG_PASSPHRASE)
          GPG_SIGNING_KEY: $(GPG_SIGNING_KEY)
          NEXUS_USERNAME: $(NEXUS_USERNAME)
          NEXUS_PASSWORD: $(NEXUS_PASSWORD)
          MVN_ARGS: "-e -V -B"
        displayName: "Deploy Java artifacts"