# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Stages
stages:
  - stage: java_build
    displayName: Java build
    jobs:
      - template: 'templates/jobs/build_java.yaml'
  - stage: java_deploy
    displayName: Deploy Java
    # Deploy Strimzi Java artifacts -> run only on main branch (where it deploys to OSS snapshot repos)
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - template: 'templates/jobs/deploy_java.yaml'
        parameters:
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
